controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Routes pour l'authetification
app_login:
    path: /login

# Routes pour Swagger UI
app_swagger:
    path: /
    controller: App\Controller\Swagger\SwaggerController::index

# Routes pour Swagger UI du module Core|Profile|Reset
app_swagger_module:
    path: /{module}
    controller: App\Controller\Swagger\SwaggerController::module
    requirements:
        module: core|acct|projet|dcao|rh|com|forms|profile|reset|security
