security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    role_hierarchy:
        ROLE_ADMIN:         [ ROLE_USER ]
        ROLE_SUPER_ADMIN:   [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            # Définir ici ton provider utilisateur, par exemple :
            entity:
                class: App\Entity\Core\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        # Firewall pour le refresh token
        refresh:
            pattern: ^/api/token/refresh
            stateless: true
            refresh_jwt: ~
            
        login:
            pattern: ^/login
            stateless: true # Pas de session
            provider: app_user_provider

            # Gère l'authentification via JSON Login pour obtenir le token
            json_login:
                check_path: /login
                username_path: username
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            
            # configure the maximum login attempts in a custom period of time
            login_throttling:
                max_attempts: 5
                interval: '3 minutes'
            
            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true
            # switch_user: { role: CAN_SWITCH_USER }
            # https://127.0.0.1:8000/?_switch_user=username
        
        # Firewall principal pour l'API (app_login)
        # Firewall principal pour les API du module Core
        app_core:
            pattern:   ^/core # Toutes les routes de l'API Core sont protégées
            stateless: true # Pas de session
            jwt: ~
            # https://symfony.com/doc/current/security/impersonating_user.html
            switch_user:
                parameter: _switch_user      # Paramètre utilisé dans l'URL
                role: ROLE_ADMIN             # Rôle requis pour utiliser cette fonctionnalité
                # https://127.0.0.1:8000/?_switch_user=username
            
        # Firewall principal pour les API du module Acct
        app_acct:
            pattern:   ^/acct # Toutes les routes de l'API Acct sont protégées
            stateless: true # Pas de session
            jwt: ~
            # https://symfony.com/doc/current/security/impersonating_user.html
            switch_user:
                parameter: _switch_user      # Paramètre utilisé dans l'URL
                role: ROLE_ADMIN             # Rôle requis pour utiliser cette fonctionnalité
                # https://127.0.0.1:8000/?_switch_user=username

        # Firewall principal pour les API du module com
        app_com:
            pattern:   ^/com # Toutes les routes de l'API Acct sont protégées
            stateless: true # Pas de session
            jwt: ~
            # https://symfony.com/doc/current/security/impersonating_user.html
            switch_user:
                parameter: _switch_user      # Paramètre utilisé dans l'URL
                role: ROLE_ADMIN             # Rôle requis pour utiliser cette fonctionnalité
                # https://127.0.0.1:8000/?_switch_user=username
            
        # Firewall principal pour les API du module projet
        app_projet:
            pattern:   ^/projet # Toutes les routes de l'API projet sont protégées
            stateless: true # Pas de session
            jwt: ~
            # https://symfony.com/doc/current/security/impersonating_user.html
            switch_user:
                parameter: _switch_user      # Paramètre utilisé dans l'URL
                role: ROLE_ADMIN             # Rôle requis pour utiliser cette fonctionnalité
                # https://127.0.0.1:8000/?_switch_user=username
            
        # Firewall principal pour les API du module dcao
        app_dcao:
            pattern:   ^/dcao # Toutes les routes de l'API dcao sont protégées
            stateless: true # Pas de session
            jwt: ~
            # https://symfony.com/doc/current/security/impersonating_user.html
            switch_user:
                parameter: _switch_user      # Paramètre utilisé dans l'URL
                role: ROLE_ADMIN             # Rôle requis pour utiliser cette fonctionnalité
                # https://127.0.0.1:8000/?_switch_user=username

         # Firewall principal pour les API du module rh
        app_rh:
            pattern:   ^/rh # Toutes les routes de l'API rh sont protégées
            stateless: true # Pas de session
            jwt: ~
            # https://symfony.com/doc/current/security/impersonating_user.html
            switch_user:
                parameter: _switch_user      # Paramètre utilisé dans l'URL
                role: ROLE_ADMIN             # Rôle requis pour utiliser cette fonctionnalité
                # https://127.0.0.1:8000/?_switch_user=username
        app_forms:
            pattern:   ^/forms # Toutes les routes de l'API rh sont protégées
            stateless: true # Pas de session
            jwt: ~
            # https://symfony.com/doc/current/security/impersonating_user.html
            switch_user:
                parameter: _switch_user      # Paramètre utilisé dans l'URL
                role: ROLE_ADMIN             # Rôle requis pour utiliser cette fonctionnalité
                # https://127.0.0.1:8000/?_switch_user=username

        # Firewall principal pour les API du module Profile
        app_profile:
            pattern:   ^/profile # Toutes les routes de l'API Profile sont protégées
            stateless: true # Pas de session
            jwt: ~
            # https://symfony.com/doc/current/security/impersonating_user.html
            switch_user:
                parameter: _switch_user      # Paramètre utilisé dans l'URL
                role: ROLE_ADMIN             # Rôle requis pour utiliser cette fonctionnalité
                # https://127.0.0.1:8000/?_switch_user=username

        # Firewall pour les utilisateurs réguliers (app_login)
        main:
            lazy: true
            provider: app_user_provider

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # 
        - { path: ^/core/, roles: ROLE_USER }
        - { path: ^/profile/, roles: ROLE_USER }
        - { path: ^/acct/, roles: ROLE_USER }
        - { path: ^/projet/, roles: ROLE_USER }
        - { path: ^/com/, roles: ROLE_USER }
        - { path: ^/rh/, roles: ROLE_USER }
        - { path: ^/forms/, roles: ROLE_USER }
        # - { path: ^/profile/, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
